language: python
python:
  - "2.7"

before_install:
  - pip install --user codecov coverage

install:
  - "pip install -r requirements.txt --use-mirrors"
script: sh -x run_travis_tests.sh

after_success:
  - codecov